/*
 *  This file is part of AQUAgpusph, a free CFD program based on SPH.
 *  Copyright (C) 2012  Jose Luis Cercos Pita <jl.cercos@upm.es>
 *
 *  AQUAgpusph is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  AQUAgpusph is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with AQUAgpusph.  If not, see <http://www.gnu.org/licenses/>.
 */

/** @file
 * @brief Complex tool to perform the link-list based on the "pos" array.
 * (See Aqua::CalcServer::LinkList for details)
 * @note Hardcoded versions of the files CalcServer/LinkList.cl.in and
 * CalcServer/LinkList.hcl.in are internally included as a text array.
 */

#ifndef LINKLIST_H_INCLUDED
#define LINKLIST_H_INCLUDED

#include "aquagpusph/sphPrerequisites.hpp"
#include <vector>
#include "Tool.hpp"
#include "Reduction.hpp"

namespace Aqua {
namespace CalcServer {

/** @class LinkList LinkList.h CalcServer/LinkList.h
 * @brief Complex tool to perform the link-list based on an array. This
 * tool include the following steps:
 *   -# Minimum and maximum positions computations
 *   -# Number of cells calculation
 *   -# "ihoc" array allocation
 *   -# "ihoc" and "icell" calculations
 *   -# Radix sort of "icell", computing permutation array "id_sorted" and
 * "id_unsorted" as well.
 * @note Hardcoded versions of the files CalcServer/LinkList.cl.in and
 * CalcServer/LinkList.hcl.in are internally included as a text array.
 * @warning This tool is assuming that "support" and "h" variables remains
 * constant
 */
class LinkList : public Aqua::CalcServer::Tool
{
  public:
	/** Constructor.
	 * @param tool_name Tool name.
	 * @param input Input array to be used as the particles positions.
	 * @param input_min Minimum of the particles positions.
	 * @param input_max Maximum of the particles positions.
	 * @param ihoc Head of cells array.
	 * @param icell Cell of each particle.
	 * @param n_cells Number of cells.
	 * @param permutations Variable where the permutations will be stored.
	 * @param inv_permutations Variable where the inverse permutations will be
	 * stored.
	 * @param recompute_grid Should be @p input_min and @p input_max
	 * recomputed or readed from the variables.
	 * @param sorter The sorting tool, either "bitonic" or "radix-sort"
	 * @param once Run this tool just once. Useful to make initializations.
	 * @note @p ihoc array is marked as reallocatable with
	 * Aqua::InputOutput::ArrayVariable::reallocatable(), since it might need
	 * to be extended
	 */
	LinkList(const std::string tool_name,
	         const std::string input = "r",
	         const std::string input_min = "r_min",
	         const std::string input_max = "r_max",
	         const std::string ihoc = "ihoc",
	         const std::string icell = "icell",
	         const std::string n_cells = "n_cells",
	         const std::string permutations = "id_unsorted",
	         const std::string inv_permutations = "id_sorted",
	         bool recompute_grid = true,
	         const std::string sorter = "radix-sort",
	         bool once = false);

	/** Destructor
	 */
	~LinkList();

	/** Initialize the tool.
	 */
	void setup();

	/** @brief Get the user event generated by this tool to mark when ncells
	 * have been successfully computed and the required memory allocated
	 *
	 * @return The event
	 */
	inline cl_event getUserEvent() const { return _user_event; }

  protected:
	/** @brief Compute the number of cells
	 * @note This method is publicly available to make it accessible from an
	 * OpenCL callback
	 */
	template<typename T>
	void nCells();

	/** @brief Allocate the "ihoc" array
	 * @note This method is publicly available to make it accessible from an
	 * OpenCL callback
	 */
	void allocate();

	/** @brief Update the changed variables.
	 * @note This method is publicly available to make it accessible from an
	 * OpenCL callback
	 */
	void setVariables();

	/** Execute the tool
	 * @param events List of events that shall be waited before safe execution
	 * @return OpenCL event to be waited before accessing the dependencies
	 */
	cl_event _execute(const std::vector<cl_event> events);

  private:
	inline uivec4 nCells32() const {
		uivec4 n_cells;
		for (unsigned int i = 0; i < 4; i++)
			n_cells.s[i] = narrow_cast<uicl>(_n_cells.s[i]);
		return n_cells;
	}

	/** Setup the OpenCL stuff
	 */
	void setupOpenCL();

	/// Input variable name
	std::string _input_name;

	/// Minimum of the input variable name
	std::string _input_min_name;

	/// Maximum of the input variable name
	std::string _input_max_name;

	/// Head of chains variable name
	std::string _ihoc_name;

	/// Cells of each particle variable name
	std::string _icell_name;

	/// Number of cells variable name
	std::string _n_cells_name;

	/// Cells length
	float _cell_length;

	/// Number of cells
	ulvec4 _n_cells;

	/// Minimum position computation tool
	Reduction* _min_pos;

	/// Maximum position computation tool
	Reduction* _max_pos;

	/// Shall be the maximum and minimum positions recomputed
	bool _recompute_minmax;

	/// Sorting by cells computation tool
	Tool* _sort;

	/// "ihoc" array initialization
	cl_kernel _ihoc;
	/// "ihoc" array initialization local work size
	size_t _ihoc_lws;
	/// "ihoc" array initialization global work size
	size_t _ihoc_gws;
	/// "ihoc" array initialization sent arguments
	std::vector<void*> _ihoc_args;

	/// "icell" array computation
	cl_kernel _icell;
	/// "icell" array computation local work size
	size_t _icell_lws;
	/// "icell" array computation global work size
	size_t _icell_gws;
	/// "icell" array computation sent arguments
	std::vector<void*> _icell_args;

	/// "ihoc" array computation
	cl_kernel _ll;
	/// "ihoc" array computation local work size
	size_t _ll_lws;
	/// "ihoc" array computation global work size
	size_t _ll_gws;
	/// "ihoc" array computation sent arguments
	std::vector<void*> _ll_args;

	/// Convenient storage of the event to make easier to work with the
	/// callback
	cl_event _user_event;
};

}
} // namespace

#endif // LINKLIST_H_INCLUDED
