set(EXAMPLE_ORIG_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src)
file(GLOB_RECURSE FNAMES RELATIVE ${EXAMPLE_ORIG_DIR} "*")
foreach(FNAME ${FNAMES})
    configure_file(${EXAMPLE_ORIG_DIR}/${FNAME}
        ${CMAKE_CURRENT_BINARY_DIR}/${FNAME} COPYONLY)
endforeach()

file(RELATIVE_PATH RUN_REL_PATH ${CMAKE_SOURCE_DIR} ${EXAMPLE_ORIG_DIR}/Create.py)
get_filename_component(EXAMPLE_REL_PATH ${RUN_REL_PATH} PATH)
set(EXAMPLE_INSTALL_DIR ${CMAKE_INSTALL_DATADIR}/${EXAMPLE_REL_PATH}/..)
cmake_path(NORMAL_PATH EXAMPLE_INSTALL_DIR)
install(
    DIRECTORY
        ${EXAMPLE_ORIG_DIR}/
    DESTINATION
        ${EXAMPLE_INSTALL_DIR}
    FILES_MATCHING
    PATTERN "*"
    PATTERN "runAll.sh" EXCLUDE
)

INSTALL(
    FILES
        ${EXAMPLE_ORIG_DIR}/runAll.sh
    DESTINATION
        ${EXAMPLE_INSTALL_DIR}
    PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ
                GROUP_EXECUTE             GROUP_READ
                WORLD_EXECUTE             WORLD_READ
)
